/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#091426",
        "primary-container": "#1e293b",
        "on-primary": "#ffffff",
        "on-primary-container": "#8590a6",
        "secondary": "#0051d5",
        "secondary-container": "#316bf3",
        "on-secondary": "#ffffff",
        "tertiary": "#00190e",
        "tertiary-container": "#00301f",
        "tertiary-fixed": "#85f8c4",
        "tertiary-fixed-dim": "#68dba9",
        "on-tertiary": "#ffffff",
        "background": "#faf8ff",
        "surface": "#faf8ff",
        "surface-bright": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "surface-variant": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#45474c",
        "outline": "#75777d",
        "outline-variant": "#c5c6cd",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        arabic: ["'IBM Plex Sans Arabic'", "'IBM Plex Sans'", "sans-serif"],
        sans: ["'IBM Plex Sans Arabic'", "Inter", "'IBM Plex Sans'", "sans-serif"],
        mono: ["'IBM Plex Mono'", "Inter", "monospace"],
      },
    },
  },
  plugins: [],
}
