import postgres from 'postgres';
import { createHash, randomBytes, createCipheriv } from 'node:crypto';
const databaseUrl=process.env.DATABASE_URL?.trim(); const master=process.env.FACTORY_BYOK_MASTER_KEY?.trim();
if(!databaseUrl) throw new Error('DATABASE_URL_REQUIRED'); if(!master) throw new Error('BYOK_MASTER_KEY_REQUIRED');
const sql=postgres(databaseUrl,{max:1}); const tenant='factory-persistence-smoke-v1'; const runId='factory-work:persistence-smoke'; const credentialRef='fake-persistence-credential'; const fakeSecret='FAKE_TEST_CREDENTIAL_DO_NOT_USE_2026';
const config={mode:'custom',providers:[{id:'test-provider',name:'Persistence Test',kind:'fake',credentialRef,enabled:true}],models:[{id:'test-model',providerId:'test-provider',modelKey:'fake-model',displayName:'Fake Model',capabilities:['test'],enabled:true}],agents:[{id:'test-agent',name:'Persistence Agent',kind:'custom',enabled:true}],roles:[{role:'tester',agentId:'test-agent',modelId:'test-model'}]};
function encrypt(secret:string){const key=createHash('sha256').update(master!).digest();const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',key,iv);const encrypted=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return {ciphertext:encrypted.toString('base64'),iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64')}}
async function ensure(){await sql.unsafe("create table if not exists factory_runtime_brain (tenant_id text not null,run_id text not null,section text not null,content_json text not null default 'null',version integer not null default 1,updated_at timestamptz not null default now(),primary key(tenant_id,run_id,section))");await sql.unsafe("create table if not exists factory_runtime_config (tenant_id text primary key,config_json text not null,updated_at timestamptz not null default now())");await sql.unsafe("create table if not exists factory_runtime_usage (id bigserial primary key,tenant_id text not null,project_id text,source text not null,provider text,model text,input_tokens integer not null default 0,output_tokens integer not null default 0,cost_micros bigint not null default 0,occurred_at timestamptz not null default now())");await sql.unsafe("create table if not exists factory_byok_vault (tenant_id text not null,credential_ref text not null,provider text not null,ciphertext text not null,iv text not null,tag text not null,updated_at timestamptz not null default now(),primary key(tenant_id,credential_ref))");}
async function write(){await ensure();const brain=JSON.stringify({marker:'project-brain-persistence-v1',safe:true});await sql.unsafe('insert into factory_runtime_brain(tenant_id,run_id,section,content_json,version) values($1,$2,$3,$4,1) on conflict(tenant_id,run_id,section) do update set content_json=excluded.content_json,version=factory_runtime_brain.version+1,updated_at=now()',[tenant,runId,'requirements',brain]);const cfg=JSON.stringify(config);await sql.unsafe('insert into factory_runtime_config(tenant_id,config_json) values($1,$2) on conflict(tenant_id) do update set config_json=excluded.config_json,updated_at=now()',[tenant,cfg]);await sql.unsafe('delete from factory_runtime_usage where tenant_id=$1',[tenant]);await sql.unsafe('insert into factory_runtime_usage(tenant_id,project_id,source,provider,model,input_tokens,output_tokens,cost_micros) values($1,$2,$3,$4,$5,$6,$7,$8)',[tenant,'persistence-smoke','customer','fake','fake-model',11,7,123]);const enc=encrypt(fakeSecret);await sql.unsafe('insert into factory_byok_vault(tenant_id,credential_ref,provider,ciphertext,iv,tag) values($1,$2,$3,$4,$5,$6) on conflict(tenant_id,credential_ref) do update set provider=excluded.provider,ciphertext=excluded.ciphertext,iv=excluded.iv,tag=excluded.tag,updated_at=now()',[tenant,credentialRef,'fake-provider',enc.ciphertext,enc.iv,enc.tag]);console.log(JSON.stringify({type:'PERSISTENCE_SMOKE_WRITE',tenant,brain:true,config:true,usage:true,byok:true,secretPrinted:false}));}
async function verify(){await ensure();const brain=await sql.unsafe('select content_json from factory_runtime_brain where tenant_id=$1 and run_id=$2 and section=$3',[tenant,runId,'requirements']);const cfg=await sql.unsafe('select config_json from factory_runtime_config where tenant_id=$1',[tenant]);const usage=await sql.unsafe('select count(*)::int events,sum(input_tokens)::int input_tokens,sum(output_tokens)::int output_tokens,sum(cost_micros)::bigint cost_micros from factory_runtime_usage where tenant_id=$1',[tenant]);const byok=await sql.unsafe('select credential_ref,provider,length(ciphertext)::int cipher_length from factory_byok_vault where tenant_id=$1 and credential_ref=$2',[tenant,credentialRef]);const ok=String(brain[0]?.content_json).includes('project-brain-persistence-v1')&&String(cfg[0]?.config_json)===JSON.stringify(config)&&Number(usage[0]?.events)===1&&Number(usage[0]?.input_tokens)===11&&Number(usage[0]?.output_tokens)===7&&Number(usage[0]?.cost_micros)===123&&byok[0]?.credential_ref===credentialRef&&Number(byok[0]?.cipher_length)>0;if(!ok)throw new Error('PERSISTENCE_SMOKE_VERIFY_FAILED');console.log(JSON.stringify({type:'PERSISTENCE_SMOKE_VERIFY',tenant,brain:true,config:true,usage:true,byokMetadata:true,rawSecretReturned:false,status:'PASS'}));}
async function cleanup(){await sql.unsafe('delete from factory_runtime_brain where tenant_id=$1',[tenant]);await sql.unsafe('delete from factory_runtime_config where tenant_id=$1',[tenant]);await sql.unsafe('delete from factory_runtime_usage where tenant_id=$1',[tenant]);await sql.unsafe('delete from factory_byok_vault where tenant_id=$1',[tenant]);console.log(JSON.stringify({type:'PERSISTENCE_SMOKE_CLEANUP',tenant,status:'PASS'}));}
const mode=process.argv[2];try{if(mode==='write')await write();else if(mode==='verify')await verify();else if(mode==='cleanup')await cleanup();else throw new Error('USE_write_verify_cleanup')}finally{await sql.end();}